export const CONSUMER_ERROR_CODES = [
  "HUB_NOT_BUILT",
  "BROWSER_NOT_LAUNCHED",
  "PROFILE_NOT_FOUND",
  "TARGET_PAGE_MISSING",
  "LOGIN_REQUIRED",
  "CAPABILITY_DB_NOT_INIT",
  "COMMAND_TIMEOUT",
  "INVALID_ARGS",
  "INVALID_JSON",
  "POLICY_APPROVAL_REQUIRED",
  "IFRAME_NOT_FOUND",
  "ELEMENT_NOT_FOUND",
  "ELEMENT_OUT_OF_VIEWPORT",
  "ARTIFACT_DOWNLOAD_TIMEOUT",
  "ARTIFACT_VERIFICATION_FAILED",
  "DOCX_VERIFICATION_FAILED",
  "POSTCONDITION_TIMEOUT",
  "RESUME_REQUIRES_CONFIRMATION",
  "IDEMPOTENCY_MISMATCH",
  "PROFILE_LOCKED",
  "PROFILE_LEASE_BUSY",
  "SAFE_OUTPUT_REDACTION_REQUIRED",
  "PLAN_OR_QUOTA_REQUIRED",
  "MODEL_SELECTION_DRIFT",
  "ARTIFACT_MODE_UNSUPPORTED",
  "AUTO_PUBLISH_DETECTED",
  "MODE_UNCERTAIN",
  "HUMAN_HANDOFF_REQUIRED",
  "UNKNOWN",
  "SENSITIVE_CONTENT_GUARD",
  "SUBMCP_QUOTA_EXHAUSTED",
  "SUBMCP_NOT_PROVISIONED",
  "UI_DRIFT_DETECTED",
  "HEAL_CONFIDENCE_LOW",
  "PROFILE_LEASE_TIMEOUT",
  "TAB_LEASE_EXPIRED",
  "CHROME_EXTENSION_NOT_CONNECTED",
  "CHROME_EXTENSION_PERMISSION_DENIED",
  "CHROME_EXTENSION_DEBUGGER_UNAVAILABLE"
] as const;

export type ConsumerErrorCode = typeof CONSUMER_ERROR_CODES[number];

export const ConsumerErrorCodes: Record<ConsumerErrorCode, ConsumerErrorCode> = Object.freeze(
  CONSUMER_ERROR_CODES.reduce((acc, code) => {
    acc[code] = code;
    return acc;
  }, {} as Record<ConsumerErrorCode, ConsumerErrorCode>)
);

export function isConsumerErrorCode(value: unknown): value is ConsumerErrorCode {
  return typeof value === "string" && (CONSUMER_ERROR_CODES as readonly string[]).includes(value);
}
